#pragma once

enum NETCODE : int
{
	FAIL = 0,
	NONE = 1,

	ERROR_SENDBUFFER_FULL = 100,
	ERROR_RECV_SOCKET = 101,
	ERROR_ACCEPT_SOCKET = 102,
	
	INFO_CLIENT_LEFT = 200,
	INFO_ACCEPT_NONBLOCKED = 201,
	INFO_CLIENT_POOL_FULL = 202,
};